### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#1]
![s](https://cloud.githubusercontent.com/assets/8947026/6075632/62f8d07e-ae11-11e4-8e0a-41c3709986b2.png)

**Comment by liach** [comment]
...

**Comment by liach** [comment]
fixed by https://github.com/Minecraft-GoodTime/GoodTime-Industrial/commit/06ada9b1d1c725bc488129d61c9b84d8c3d27e51?
