### ISSUE TITLE
Fix style

### ISSUE THREAD

**Issue by liach** [GoodTimeStudio/GoodTime-Industrial#11]
1156407698, you should improve your style... As you cannot see it on travis-ci, run build.bat and you can see lots of warnings.

**Comment by BestOwl** [comment]
ok

**Comment by liach** [comment]
I fixed a lot, waiting for https://travis-ci.org/Minecraft-GoodTime/GoodTime-Industrial/builds/60313233

**Comment by liach** [comment]
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/blocks/BlockWaterHyacinth.java:89:96: warning: '&&' should be on a new line.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/blocks/OreIridium.java:0: warning: File does not end with a newline.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/blocks/machines/GenGasKu.java:30: warning: Wrong lexicographical order for 'com.mcgoodtime.gti.common.core.GuiHandler' import.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/blocks/machines/GenGasKu.java:31: warning: Wrong lexicographical order for 'com.mcgoodtime.gti.common.core.Gti' import.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/fluid/Gas.java:0: warning: File does not end with a newline.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/fluid/Gas.java:32: warning: '.' have incorrect indentation level 4, expected level should be 8.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/fluid/fluidblock/FluidBlockGas.java:0: warning: File does not end with a newline.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/init/GtiItems.java:28: warning: Wrong lexicographical order for 'com.mcgoodtime.gti.common.items.crushed.CrushedIridium' import.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/ItemWaterHyacinth.java:73:117: warning: '&&' should be on a new line.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/ItemWaterHyacinth.java:76:112: warning: '.' should be on a new line.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:35: warning: 'ctor def modifier' have incorrect indentation level 8, expected level should be 4.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:35:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:36:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:37: warning: 'ctor def' child have incorrect indentation level 16, expected level should be 8.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:37:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:38: warning: 'ctor def' child have incorrect indentation level 16, expected level should be 8.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:38:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:39: warning: 'ctor def' child have incorrect indentation level 16, expected level should be 8.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:39:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:40: warning: 'ctor def' child have incorrect indentation level 16, expected level should be 8.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:40:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:41: warning: 'ctor def rcurly' have incorrect indentation level 8, expected level should be 4.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/food/DiamondApple.java:41:1: warning: Line contains a tab character.
[ant:checkstyle] src/main/java/com/mcgoodtime/gti/common/items/tools/IridiumPickaxe.java:28: warning: 'com.mcgoodtime.gti.common.init.GtiItems'should be separated from previous import group.
