### ISSUE TITLE
Multiple Texture

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#16]
Multiple texture change with the direction of the block is placed.Just like ic2 machines.

**Comment by liach** [comment]
http://www.hakugyokurou.net/wordpress/?page_id=126

**Comment by BestOwl** [comment]
?

**Comment by liach** [comment]
...

**Comment by BestOwl** [comment]
I don't understand ， what should i do?

**Comment by liach** [comment]
好吧……先看教程?

**Comment by BestOwl** [comment]
😂 然而教程并没有关于多面材质的

**Comment by Java0** [comment]
我的密码重置了⁽⁽◝( ˙ ꒳ ˙ )◜⁾⁾

**Comment by BestOwl** [comment]
I think I found a way to solve the problem of the Multiple Texture, but i need time.

**Comment by liach** [comment]
@BestOwl @Java0 Is there still anything wrong?

**Comment by BestOwl** [comment]
Fixed
