### ISSUE TITLE
jenkins build number

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#18]
show jenkins build number in the mod version.
![0](https://cloud.githubusercontent.com/assets/8947026/7724060/a6de8b5c-ff20-11e4-9daf-65bcd1558525.png)

**Comment by liach** [comment]
Will use gradle to replace.

**Comment by liach** [comment]
Not a good idea to use it actually.

**Comment by BestOwl** [comment]
why?

**Comment by liach** [comment]
It's too difficult, and not needed.
