### ISSUE TITLE
Checkstyle unable to create a Checker

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#23]
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/mnt/jenkins/workspace/Gti/build.gradle'.
Included projects: [root project 'Gti']
Evaluating root project 'Gti' using build file '/mnt/jenkins/workspace/Gti/build.gradle'.

---

 Powered By MCP:  
 http://mcp.ocean-labs.de/  
 Searge, ProfMobius, Fesh0r, 
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown

---

All projects evaluated.
Selected primary task 'clean' from project :
Selected primary task 'setupCIWorkspace' from project :
Selected primary task 'changeBuildNum' from project :
Selected primary task 'build' from project :
Tasks to be executed: [task ':clean', task ':downloadClient', task ':downloadServer', task ':getVersionJson', task ':extractUserDev', task ':mergeJars', task ':applyBinPatches', task ':downloadMcpTools', task ':extractMcpData', task ':genSrgs', task ':deobfBinJar', task ':setupCIWorkspace', task ':changeBuildNum', task ':compileApiJava', task ':processApiResources', task ':apiClasses', task ':checkstyleApi', task ':sourceMainJava', task ':compileJava', task ':processResources', task ':classes', task ':checkstyleMain', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':checkstyleTest', task ':test', task ':check', task ':jar', task ':reobf', task ':assemble', task ':build']
:clean (Thread[main,5,main]) started.
:clean
Executing task ':clean' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
:clean (Thread[main,5,main]) completed. Took 0.089 secs.
:downloadClient (Thread[main,5,main]) started.
:downloadClient
Skipping task ':downloadClient' as task onlyIf is false.
:downloadClient SKIPPED
:downloadClient (Thread[main,5,main]) completed. Took 0.513 secs.
:downloadServer (Thread[main,5,main]) started.
:downloadServer
Skipping task ':downloadServer' as task onlyIf is false.
:downloadServer SKIPPED
:downloadServer (Thread[main,5,main]) completed. Took 0.624 secs.
:getVersionJson (Thread[main,5,main]) started.
:getVersionJson
Executing task ':getVersionJson' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
:getVersionJson (Thread[main,5,main]) completed. Took 1.789 secs.
:extractUserDev (Thread[main,5,main]) started.
:extractUserDev
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/net/minecraftforge/forge/1.7.10-10.13.4.1481-1.7.10/forge-1.7.10-10.13.4.1481-1.7.10.pom]
Skipping task ':extractUserDev' as it is up-to-date (took 4.364 secs).
:extractUserDev UP-TO-DATE
:extractUserDev (Thread[main,5,main]) completed. Took 4.366 secs.
:mergeJars (Thread[main,5,main]) started.
:mergeJars
Skipping task ':mergeJars' as task onlyIf is false.
:mergeJars SKIPPED
:mergeJars (Thread[main,5,main]) completed. Took 1.419 secs.
:applyBinPatches (Thread[main,5,main]) started.
:applyBinPatches
Skipping task ':applyBinPatches' as task onlyIf is false.
:applyBinPatches SKIPPED
:applyBinPatches (Thread[main,5,main]) completed. Took 0.734 secs.
:downloadMcpTools (Thread[main,5,main]) started.
:downloadMcpTools
Skipping task ':downloadMcpTools' as task onlyIf is false.
:downloadMcpTools SKIPPED
:downloadMcpTools (Thread[main,5,main]) completed. Took 0.012 secs.
:extractMcpData (Thread[main,5,main]) started.
:extractMcpData
Skipping task ':extractMcpData' as it is up-to-date (took 0.004 secs).
:extractMcpData UP-TO-DATE
:extractMcpData (Thread[main,5,main]) completed. Took 0.004 secs.
:genSrgs (Thread[main,5,main]) started.
:genSrgs
Skipping task ':genSrgs' as task onlyIf is false.
:genSrgs SKIPPED
:genSrgs (Thread[main,5,main]) completed. Took 0.345 secs.
:deobfBinJar (Thread[main,5,main]) started.
:deobfBinJar
Skipping task ':deobfBinJar' as task onlyIf is false.
:deobfBinJar SKIPPED
:deobfBinJar (Thread[main,5,main]) completed. Took 0.757 secs.
:setupCIWorkspace (Thread[main,5,main]) started.
:setupCIWorkspace
Skipping task ':setupCIWorkspace' as it has no actions.
:setupCIWorkspace UP-TO-DATE
:setupCIWorkspace (Thread[main,5,main]) completed. Took 0.002 secs.
:changeBuildNum (Thread[main,5,main]) started.
:changeBuildNum
Executing task ':changeBuildNum' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:changeBuildNum (Thread[main,5,main]) completed. Took 0.081 secs.
:compileApiJava (Thread[main,5,main]) started.
:compileApiJava
Skipping task ':compileApiJava' as it has no source files.
:compileApiJava UP-TO-DATE
:compileApiJava (Thread[main,5,main]) completed. Took 0.002 secs.
:processApiResources (Thread[main,5,main]) started.
:processApiResources
Skipping task ':processApiResources' as it has no source files.
:processApiResources UP-TO-DATE
:processApiResources (Thread[main,5,main]) completed. Took 0.009 secs.
:apiClasses (Thread[main,5,main]) started.
:apiClasses
Skipping task ':apiClasses' as it has no actions.
:apiClasses UP-TO-DATE
:apiClasses (Thread[main,5,main]) completed. Took 0.001 secs.
:checkstyleApi (Thread[main,5,main]) started.
:checkstyleApi
Skipping task ':checkstyleApi' as it has no source files.
:checkstyleApi UP-TO-DATE
:checkstyleApi (Thread[main,5,main]) completed. Took 0.002 secs.
:sourceMainJava (Thread[main,5,main]) started.
:sourceMainJava
Executing task ':sourceMainJava' (up-to-date check took 0.049 secs) due to:
  Output file /mnt/jenkins/workspace/Gti/build/sources/java has changed.
  Output file /mnt/jenkins/workspace/Gti/build/sources/java/com/mcgoodtime/gti/client/gui/GuiCarbonizeFurnace.java has been removed.
  Output file /mnt/jenkins/workspace/Gti/build/sources/java/com/mcgoodtime/gti/common/blocks/BlockWaterHyacinth.java has been removed.
:sourceMainJava (Thread[main,5,main]) completed. Took 0.254 secs.
:compileJava (Thread[main,5,main]) started.
:compileJava
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/net/industrial-craft/industrialcraft-2/2.2.742-experimental/industrialcraft-2-2.2.742-experimental.pom]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net//forgeBin/1.7.10-10.13.4.1481-1.7.10/forgeBin-1.7.10-10.13.4.1481-1.7.10.pom]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.pom]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.pom]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.pom]
file or directory '/mnt/jenkins/workspace/Gti/libs', not found
Executing task ':compileJava' (up-to-date check took 6.137 secs) due to:
  Output file /mnt/jenkins/workspace/Gti/build/classes/main has changed.
  Output file /mnt/jenkins/workspace/Gti/build/dependency-cache has changed.
  Output file /mnt/jenkins/workspace/Gti/build/classes/main/com/mcgoodtime/gti/common/core/GtiConfig.class has been removed.
All input files are considered out-of-date for incremental task ':compileJava'.
file or directory '/mnt/jenkins/workspace/Gti/libs', not found
Compiling with JDK Java compiler API.
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:compileJava (Thread[main,5,main]) completed. Took 9.881 secs.
:processResources (Thread[main,5,main]) started.
:processResources
Executing task ':processResources' (up-to-date check took 0.073 secs) due to:
  Value of input property 'version' has changed for task ':processResources'
:processResources (Thread[main,5,main]) completed. Took 0.911 secs.
:classes (Thread[main,5,main]) started.
:classes
Skipping task ':classes' as it has no actions.
:classes (Thread[main,5,main]) completed. Took 0.001 secs.
:checkstyleMain (Thread[main,5,main]) started.
:checkstyleMain
Executing task ':checkstyleMain' (up-to-date check took 0.109 secs) due to:
  No history is available.
:checkstyleMain FAILED
:checkstyleMain (Thread[main,5,main]) completed. Took 1.145 secs.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':checkstyleMain'.
  
  > Unable to create a Checker: No enum constant com.puppycrawl.tools.checkstyle.api.SeverityLevel.FATAL
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 38.099 secs
Stopped 0 compiler daemon(s).
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

**Comment by BestOwl** [comment]
@liach Please fix it.

**Comment by liach** [comment]
I'd remove your commit and force push mine to fix it.

**Comment by liach** [comment]
Oh that's a gradle bug...
