### ISSUE TITLE
FluidKineticGenerator fluid name Display error

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#31]
At the beginning, the fluid in the fluidTank is lava, and fluid name displays correctly.
However, when fluid burned to the remaining 10mb, the name start error

In fact, the fluid in the fluidTank is lava(岩浆), not Distilled water(蒸馏水).
![ku](https://cloud.githubusercontent.com/assets/8947026/11612411/ef275d3e-9c33-11e5-9127-0a71a218bf24.png)

**Comment by liach** [comment]
现在解决了吗？

**Comment by BestOwl** [comment]
还没有
