### ISSUE TITLE
There is many issues.....

### ISSUE THREAD

**Issue by Fnober** [GoodTimeStudio/GoodTime-Industrial#34]
1.干燥机内脱水水葫芦块合成在NEI内显示错位;
2.铱矿材质崩溃;
3.小块压缩水葫芦材质有白点没抠干净;
4.干货无法显示模型类材质的食物,例如ganyssuface的烤鱿鱼;
5.很多东西没有合成表(这个好像很快就能补全);
6.F3+H显示物品详细标记的时候很多物品都会显示出durability(你在逗我);
7.水葫芦好像还没做....只添加了一个物品条目;
但是总体来说这次改变很成功.......兼容性不知道比原来高到哪里去
测试用的113mods的包,具体就不说了,总之能打的开...
我记得曾经有一阵子连新版IC都不兼容,最后希望能一直做下去,因为原创优质MOD不是很多
这个MOD有潜力.

**Comment by Fnober** [comment]
There is many............英语老师我对不起你

**Comment by liach** [comment]
？

**Comment by BestOwl** [comment]
铱矿石的材质在测试的时候是正常的，不知道出了什么问题，水葫芦已经做了一半，没有弄生成，其他bug我们会尽快修复。
我们会一直做下去的。感谢你的支持！

发自我的 Windows Phone

---

Reply to this email directly or view it on GitHub:
https://github.com/GoodTimeStudio/Production-Line/issues/34
