### ISSUE TITLE
dev server seems to be down, what's up?

### ISSUE THREAD

**Issue by LemADEC** [GoodTimeStudio/GoodTime-Industrial#40]

**Comment by BestOwl** [comment]
yes, we shut down the dev server temporarily because of the funding problem, but we will reopen it next month.

**Comment by LemADEC** [comment]
Ok.


Is the mod stable enough on 1.7.10 for a public server?
Any major issues we should be aware of for 1.7.10?

**Comment by BestOwl** [comment]
Based on current known issues, there's no major issues on 1.7.10. But we still not recommend you install it to a public server, this mod hasn't been tested on the server, we don't know what it will happen. And this mod is under dev, many features are still incomplete.
