### ISSUE TITLE
SideProxy Crash

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#5]
Unkown error

**Comment by liach** [comment]
Actually the `@SidedProxy` needs to be used on a variable, which is a `CommonProxy`, just like

``` java
@SidedProxy(clientSide = "com.mcgoodtime.gti.client.ClientProxy", serverSide = "com.mcgoodtime.gti.common.core.CommonProxy")
public CommonProxy commonProxy;
```

Which the `ClientProxy` extends the `CommonProxy`, or you can make another `ServerProxy` which extends `CommonProxy`, but that's not used so often.
