### ISSUE TITLE
Develop a network system

### ISSUE THREAD

**Issue by BestOwl** [GoodTimeStudio/GoodTime-Industrial#6]
Unable to take the items in the GUI

**Comment by liach** [comment]
I think I could fix it myself... I think there's something that is related to container that's not implemented.

**Comment by liach** [comment]
yeah we need some work on network...

**Comment by BestOwl** [comment]
I think we should fix it as soon as possible

**Comment by liach** [comment]
I think it might be somewhat fixed by the commit above... @1156407698 Please test.

**Comment by BestOwl** [comment]
still not

**Comment by liach** [comment]
Um, we might need a rewrite.

**Comment by liach** [comment]
Or register TileEntity?

**Comment by BestOwl** [comment]
....... still not = =

**Comment by liach** [comment]
You might try first. I am not free recently.

**Comment by Couther** [comment]
Only you are talking.Where are the others?

**Comment by liach** [comment]
Haha @Java0 @JAVA10086 They do not work. They've just registered a github account and wait happily.

**Comment by Couther** [comment]
你们够了，说中文OK？

**Comment by liach** [comment]
@Couther You need to contribute some day...

**Comment by BestOwl** [comment]
Um, this is International website, so we should use english

**Comment by BestOwl** [comment]
Develop a better network system

**Comment by BestOwl** [comment]
@liach Do you know how to cast Object to byte[] ?

**Comment by liach** [comment]
http://stackoverflow.com/questions/10730929/cast-an-object-to-bytearray

**Comment by BestOwl** [comment]
if use ObjectOutputStream, the Object must implement Serializable

**Comment by liach** [comment]
现在没问题了吧
