### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by liach** [GoodTimeStudio/GoodTime-Industrial#9]
- [ ]  Electric
  - [ ] extend from tesla coil
  - [ ] multiblock fluid generator，high efficiency，upgrades applicable
  - [x] EVSU
  - [x] CEU
  - [x] CSEU
- [ ] Machine
  - [x]  CarbonizeFurnace
  - [ ] Juicer
  - [ ] Liquid Extraction
  - [x] Dryer
  - [ ] Garbage furnace
- [ ] Kinetic
  - [ ] ku container
  - [x] `gengasku` to `fluidgenku`
  - [ ] bronze lathing tool and bronze turning blank
  - [ ] ku detector
  - [ ] ku chargepad
  - [ ] recipes with turning blank
- [ ] Heat
  - [ ] hu container
  - [ ] hu trader
  - [ ] hu centrifuge？
- [x] world gen
  - [x] iridium
  - [x] basalt
- [ ] others
  - [x] throwable uranium
  - [x] throwable salt
  - [x] add water hyacinth
  - [x] add more tree taps
  - [ ] special containers for special fluid

**Comment by JAVA10086** [comment]
23333

**Comment by Java0** [comment]
呃，是在这里发脑洞么＠(￣-￣)＠

**Comment by liach** [comment]
对。会不定期清理无用评论。

**Comment by liach** [comment]
- []

**Comment by Java0** [comment]
岩浆得用特定桶子装(～o～)Y

**Comment by JAVA10086** [comment]
233333


------------------ 原始邮件 ------------------
发件人: "Java0";<notifications@github.com>;
发送时间: 2015年4月4日(星期六) 中午11:31
收件人: "Minecraft-GoodTime/GoodTime-Industrial"<GoodTime-Industrial@noreply.github.com>; 
抄送: "God-death"<2251357245@qq.com>; 
主题: Re: [GoodTime-Industrial] Future Plans (#9)




岩浆得用特定桶子装(～o～)Y

**Comment by liach** [comment]
好了，我删除下重复的评论

**Comment by Java0** [comment]
会生锈的金属，和环境mod配合，太潮湿会生锈23333

**Comment by liach** [comment]
那么就是金属块？
还是背包里面有水？
还是铁路会生锈？

**Comment by Java0** [comment]
金属锭也会生锈

**Comment by Java0** [comment]
但是生锈了可以靠机器复原233

**Comment by XuyuEre** [comment]
那也太麻烦了。。或者专门做种箱子，在箱子里头的金属不会生锈，普通箱子和背包里头假设多少T后生锈，生锈后用某种物质（酸（硫酸？？））放在合成台里头处理

**Comment by XuyuEre** [comment]
如果做出来机器前所有金属都生锈了咋办，是不23333

**Comment by liach** [comment]
这个机制很麻烦，而且我们是服务器，在服务器上面用不卡死服务器就是奇迹了，精神可以和gt的tileentity的矿物比较。

**Comment by Java0** [comment]
呃

**Comment by XuyuEre** [comment]
某种装置储存动能，像手表是储存在弹簧（发条）里头的，或者我们设计一个物品就叫动能储存盒算了，然后把它放到动能发生器（做个动能座）里头冲动能

**Comment by liach** [comment]
en

**Comment by 3TUSK** [comment]
盐酸
用于清理钙化
（然后世界生成里多了岩盐（Rock Salt）……电解食盐水？）

**Comment by gxy17886** [comment]
话说现在还有人在填坑啊

**Comment by 3TUSK** [comment]
然而我只是路过的...

**Comment by 1156407698** [comment]
当然有人在填坑

**Comment by liach** [comment]
@1156407698 https://github.com/Minecraft-GoodTime/GoodTime-Industrial/blob/master/build.gradle#L5-L7
试试看在服务器搞个jenkins+maven，监测forge的github repo，发现更新立刻编译？估计能对解决问题有帮助。

**Comment by 1156407698** [comment]
OK

**Comment by BestOwl** [comment]
大型多方块蒸汽轮机（3_3_5）
{
    固体或液体燃料加热机
    液体输入输入方块
    蓄水槽
    排气口
    可视窗
    叶片
    蒸汽机
    高温隔热外壳
    高级机械外壳
    （使用固体燃料加入时，需要额外固体燃料室）
}

**Comment by BestOwl** [comment]
EVSU储电盒
EVSU充电座
输出：8192eu/t
储电量：100m eu

**Comment by BestOwl** [comment]
EVSU储电量：1E eu

**Comment by Couther** [comment]
为何要用eu为能源单位？要做工业附属？为何不开发自己的能源系统？

**Comment by liach** [comment]
工业附属

**Comment by BestOwl** [comment]
We are going to change the plan, issue closed. We will open another issue for the new future plans
